
services:
  mysql:
    image: "mysql:8"
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: u04t3fxg0imusvi7
    volumes:
      - /app/data/n9e/mysql/data:/var/lib/mysql/
      - /app/data/n9e/initsql:/docker-entrypoint-initdb.d/
      - /app/data/n9e/etc/my.cnf:/etc/my.cnf
      - /app/data/n9e/mysql/log:/var/log/mysql
    networks:
      - jwb
    ports:
      - "6001:6001"

  redis:
    image: "redis:6.2"
    container_name: redis
    hostname: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /app/data/n9e/redis:/data
    networks:
      - jwb
    ports:
      - "6002:6002"

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   hostname: prometheus
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai
  #   volumes:
  #     - ./etc-prometheus:/etc/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #     - "--web.console.templates=/usr/share/prometheus/consoles"
  #     - "--enable-feature=remote-write-receiver"
  #     - "--query.lookback-delta=2m"
  #   networks:
  #     - nightingale
  #   ports:
  #     - "9090:9090"

  # victoriametrics:
  #   image: victoriametrics/victoria-metrics:v1.79.12
  #   container_name: victoriametrics
  #   hostname: victoriametrics
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai
  #   ports:
  #     - "8428:8428"
  #   networks:
  #     - nightingale
  #   command:
  #     - "--loggerTimezone=Asia/Shanghai"

  nightingale:
    image: flashcatcloud/nightingale:v8.0.0-beta.10
    container_name: nightingale
    hostname: nightingale
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:6001, redis:6002
    volumes:
      - /app/data/n9e/etc/:/app/etc
    networks:
      - jwb
    ports:
      - "5007:5007"
      - "5008:5008"
    depends_on:
      - mysql
      - redis
      # - victoriametrics
    command: >
      sh -c "/app/n9e"

  # categraf:
  #   image: "flashcatcloud/categraf:latest"
  #   container_name: "categraf"
  #   hostname: "categraf01"
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai
  #     HOST_PROC: /hostfs/proc
  #     HOST_SYS: /hostfs/sys
  #     HOST_MOUNT_PREFIX: /hostfs
  #     WAIT_HOSTS: nightingale:17000, nightingale:20090
  #   volumes:
  #     - ./etc-categraf:/etc/categraf/conf
  #     - /:/hostfs
  #   networks:
  #     - nightingale
  #   depends_on:
  #     - nightingale
