
services:
  mysql:
    image: "mysql:8"
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: u04t3fxg0imusvi7
    volumes:
      - /app/data/n9e/mysql/data:/var/lib/mysql/
      - /app/data/n9e/initsql:/docker-entrypoint-initdb.d/
      - /app/data/n9e/etc/my.cnf:/etc/my.cnf
      - /app/data/n9e/mysql/log:/var/log/mysql
    networks:
      - jwb
    ports:
      - "6001:3306"

  redis:
    image: "redis:6.2"
    container_name: redis
    hostname: redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /app/data/n9e/redis:/data
    networks:
      - jwb
    ports:
      - "6002:6379"

  nightingale:
    image: flashcatcloud/nightingale:v8.0.0-beta.10-amd64
    container_name: nightingale
    hostname: nightingale
    restart: always
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:6001, redis:6002
    volumes:
      - /app/data/n9e/etc/:/app/etc
    networks:
      - jwb
    ports:
      - "5007:5007"
      - "5008:5008"
    depends_on:
      - mysql
      - redis
      # - victoriametrics
    command: >
      sh -c "/app/n9e"

networks:
  jwb:
    driver: bridge